civictheme/monorepo-drupal

docroot/themes/contrib/civic/civic-library/components/00-base/mixins/_visibility.scss, docroot/themes/contrib/civic/civic-library/components/01-atoms/icon/icon.scss, docroot/themes/contrib/civic/civic-library/components/02-molecules/search/search.scss, docroot/themes/contrib/civic/civic-library/components/02-molecules/skip-link/skip-link.scss, docroot/themes/contrib/civic/civic-library/components/02-molecules/skip-link/skip-link.stories.js, docroot/themes/contrib/civic/civic-library/components/02-molecules/skip-link/skip-link.twig, docroot/themes/contrib/civic/civic-library/components/03-organisms/slider/slider.scss, docroot/themes/contrib/civic/civic-library/components/03-organisms/social-links/social-links.scss, docroot/themes/contrib/civic/templates/layout/html.html.twig
https://salsadigital.atlassian.net/browse/CIVIC-576
=> [CIVIC-576] Added integration of the Skip Link with Drupal.

docroot/themes/contrib/civic/civic-library/components/03-organisms/alert/alert.js
**Issue URL:**
1.  Set the path Key-Value to '/' when setting alert dismissal cookie path, so that a dismissed alert is dismissed on all pages, not just one level up from the page it was dismissed on.
Before:
After:
Alert dismissal cookie paths are all "/".
=> Fixed alert banner cookie path so that it is dismissed on all pages.

docroot/themes/contrib/civic/civic-library/components/03-organisms/password-indicator/password-indicator.js
**Issue URL:**
1.  Fixed the password indicator. The code for the initial check for the Password indicator was broken. Fix copied from ONI.
**Before: Password indicator was not appearing as initial processed check was incorrect.**
**After: Password indicator works again.**
=> Fixed Password indicator.

docroot/themes/contrib/civic/includes/pager.inc
1. Bug with preprocess pager - fix check to look for NULL rather than false as offset can and usually is 0.
=> Fix change to civic preprocess pager.

docroot/themes/contrib/civic/civic-library/components/03-organisms/large-filter/large-filter.js, docroot/themes/contrib/civic/includes/form.inc
1. Added event for filter layout being updated (so client libraries can update based on layout)
2. Cleaned up form scss to properly hide form elements
=> Added event for mobile layout update.

docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_card_subject.field_c_p_image.yml, tests/behat/features/paragraph.civictheme_card_subject.fields.feature
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-454
1.  Updated Subject card image field as required.
=> [CIVIC-454] Updated subject card component.

docroot/themes/contrib/civictheme/civictheme-library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/side-navigation/side-navigation.scss, docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/side-navigation/side-navigation.twig
**Issue URL:** [CIVIC-575]
1.  Added side navigation spacing below by default.
2. Added classes for side navigation spacing.
=> [CIVIC-575] Added side navigation spacing.

docroot/themes/contrib/civictheme/civictheme-library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme-library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme-library/components/02-molecules/promo-card/promo-card.scss
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-587
1.  Fixed styling of date on Promo card.
=> [CIVIC-587] Fixed date styling on Promo card.

docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_card_task.yml, docroot/themes/contrib/civictheme/includes/card_task.inc, docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-card-task.html.twig, tests/behat/features/content_type.civictheme_page.view.feature, tests/behat/features/paragraph.civictheme_card_container.fields.feature, tests/behat/features/paragraph.civictheme_card_task.fields.feature
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-582
1.  Changed "Card task" to "Task card".
2. Updated tests that reference "Card task" to "Task card".
=> [CIVIC-582] Changed "Card task" to "Task card".

docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-listing.html.twig
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-569
1.  Added theme styling to listing title.
=> [CIVIC-569] Added theme styling to listing title.

docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_listing.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_listing.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_theme.yml, tests/behat/features/paragraph.civictheme_listing.fields.feature
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-616
1.  Added Theme field to Listing component.
=> [CIVIC-616] Added theme field to Listing component.

docroot/themes/contrib/civictheme/civictheme-library/components/04-templates/page/page.twig, docroot/themes/contrib/civictheme/templates/layout/html.html.twig
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-622
1.  Skip link template fix.
=> [CIVIC-622] Fixed Skip Link not having a URL.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.js
**Issue URL:**
[CIVIC-617]
1.  Updated slider button style update function to explicitly remove focus class and fire focusout envent.
=> [CIVIC-617] Fixed button focus issue.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.twig, docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/templates/form/input--submit.html.twig
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-607
1.
=> [CIVIC-607] Form element description template.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
=> [CIVIC-607] Updated link component to use hidden_text.

docroot/themes/contrib/civictheme/includes/banner.inc, tests/behat/features/content_type.civictheme_page.view.feature
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-668
1. Updated the precedence of banner breadcrumb override function to take effect.
2. Added behat test to verify the banner breadcrumb override.
=> [CIVIC-668] Updated function logic of Banner breadcrumb theme to allow overridden from page

docroot/themes/contrib/civictheme/civictheme_create_subtheme.php, docroot/themes/contrib/civictheme/civictheme_library/scripts/extract_css_colors_to_csv.php
1. Found two more required relative path replacements needed in starter theme.
2. Lint fix.
=> Add additional replacements of relative paths.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig, docroot/themes/contrib/civictheme/includes/menu.inc, docroot/themes/contrib/civictheme/includes/primary_navigation.inc, docroot/themes/contrib/civictheme/includes/secondary_navigation.inc, docroot/themes/contrib/civictheme/templates/block/block--menu-block--civictheme-footer.html.twig
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-675
1.
=> [CIVIC-675] Fixed external menu link intergration.

docroot/themes/contrib/civictheme/theme-settings.php, tests/behat/features/theme.settings.feature
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-674
1.  Added validation and submit handler to handle file path. 
2. User can provide public stream or relative URL etc.
=> [CIVIC-674] Fixed logos not handling public stream wrappers as value in theme settings.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig, docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-675
1.
=> [CIVIC-675] Mobile navigation external icon fix.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-683
1.
=> [CIVIC-683] Button to restrict with regular icon only.

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/05.component.content.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/07.component.attachment.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/08.component.callout.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/09.component.iframe.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/10.component.map.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/11.component.next_step.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/12.component.promo.inc, docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-685
Added components to demo content.
1. Attachment
2. Callout
3. Iframe
4. Map
5. Next step
6. Promo
=> [CIVIC-685] Added components to demo content.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
**Issue URL:**
1.  Fixed typo with letter spacing on mobile h3.
=> Fixed typo with letter spacing on mobile h3.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.twig
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-676
1.  Made theme render top navigation columns regardless of content.
=> [CIVIC-676] Fixed position of header top 3 region.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/video/video.twig
**Issue URL:**
1.  Fixed typos on Video component.
=> Fixed typos on Video component.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/map/map.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig, docroot/themes/contrib/civictheme/includes/media.inc
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-590
1. Converted map custom links to use button atoms
2. Converted video custom links to use button atoms.
3. Fixed video share link to use provided text if available.
4. Fixed missing space handler in basic content component.
=> [CIVIC-590] Updated Map and video - inconsistent custom links instead of a button or a link with an icon

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss
**Issue URL:**
1.  Fixed wrong color reference on Primary navigation that caused normal primary navigation headings to take on the hover color.
=> [CIVIC] Fixed wrong color reference on Primary navigation.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
**Issue URL:**
1.  Fixed bug that caused mobile navigation trigger modifier classes to render incorrectly.
2. Removed handling of theme class since this is handled in the button using the theme property.
**Before fix**
**After fix**
=> [CIVIC] Fixed mobile navigation trigger modifier class bug.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-701
1.  Fixed HTML tags rendering for Promo Card with Event CT
=> [CIVIC-701] Fixed HTML tags rendering for Promo Card with Event CT

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/13.component.listing.inc, docroot/themes/contrib/civictheme/includes/views.inc
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-704
1.  Fixed Background is applied to Listing component with unlimited and no BG.
2. Updated demo content so that the applied theme is more prominent and shown.
=> [CIVIC-703] [CIVIC-704]  Listing component - Card theme and background fix

docroot/themes/contrib/civictheme/includes/cards.inc
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-702
1. Fixed date missing in Promo Card with Event CT.
=> [CIVIC-702] Fixed date missing in Promo Card with Event CT.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-713
1.  Fixed Callout CTA when without link text.
2. Arrow is shown if link text is empty
=> [CIVIC-713] Fixed Callout CTA when without link text.

docroot/themes/contrib/civictheme/includes/node.inc, docroot/themes/contrib/civictheme/templates/content/node--civictheme-slider-slide.html.twig
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-711
1.  Fixed Reference content does not render in the Slider component
=> [CIVIC-711] Fixed Reference content does not render in the Slider component

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc, docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/04.banner.inc, docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_hide_breadcrumb.yml, docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_banner_hide_breadcrumb.yml, docroot/themes/contrib/civictheme/includes/banner.inc, tests/behat/features/content_type.civictheme_page.fields.feature, tests/behat/features/content_type.civictheme_page.view.feature
**Issue URL:**
https://salsadigital.atlassian.net/browse/CIVIC-693
1.
=> [CIVIC-693] Hide breadcrumb option in banner.

docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-684
1. Added CacheableMetadata at menu tree for links mobile menu.
https://nimb.ws/HpfdN7
https://nimb.ws/q5tXLk
=> [CIVIC-684] Fixed ‘Link’ menu field does not get updated immediately on mobile

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-708
1. Fixed Publication Card content cut-off when column count is more.
=> [CIVIC-708] Fixed Publication Card content cut-off when column count is more.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-671
1. FixedAccordion Dark colour does not apply to content inner region.
=> [CIVIC-671] Fixed Accordion Dark colour does not apply to content inner region.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig
**Issue URL:**
1.  Fixed class name on video player wrapper which caused the component to not receive the correct styling.
=> [CIVIC] Fixed video player typo.

docroot/themes/contrib/civictheme/includes/accordion.inc, docroot/themes/contrib/civictheme/includes/node.inc, docroot/themes/contrib/civictheme/includes/slider.inc, tests/behat/features/media.image.view.feature
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-721
1. Replaced all occurrences of `getValue()[0]['value']` with ->view().
=> [CIVIC-721] Fixed content fields to allow tokens and filters

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/14.component.webform.inc, docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.twig, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_webform.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_webform.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_background.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_space.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_theme.yml, docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/includes/paragraphs.inc, docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-webform.html.twig, tests/behat/features/paragraph.civictheme_webform.fields.feature, tests/behat/features/paragraph.civictheme_webform.view.feature
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-715
1.  Added Webform component to Storybook and add theme/spacing/background.
2. Updated demo content
3. Updated behat test
=> [CIVIC-715] Added Webform component to Storybook and add theme/spacing/background.

docroot/themes/contrib/civictheme/includes/attachment.inc, docroot/themes/contrib/civictheme/includes/banner.inc, docroot/themes/contrib/civictheme/includes/callout.inc, docroot/themes/contrib/civictheme/includes/card_container.inc, docroot/themes/contrib/civictheme/includes/cards.inc, docroot/themes/contrib/civictheme/includes/event_card.inc, docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/includes/iframe.inc, docroot/themes/contrib/civictheme/includes/map.inc, docroot/themes/contrib/civictheme/includes/media.inc, docroot/themes/contrib/civictheme/includes/mobile_navigation.inc, docroot/themes/contrib/civictheme/includes/navigation_card.inc, docroot/themes/contrib/civictheme/includes/next_step.inc, docroot/themes/contrib/civictheme/includes/node.inc, docroot/themes/contrib/civictheme/includes/paragraphs.inc, docroot/themes/contrib/civictheme/includes/promo.inc, docroot/themes/contrib/civictheme/includes/promo_card.inc, docroot/themes/contrib/civictheme/includes/publication_card.inc, docroot/themes/contrib/civictheme/includes/quick_links.inc, docroot/themes/contrib/civictheme/includes/service_card.inc, docroot/themes/contrib/civictheme/includes/slider.inc, docroot/themes/contrib/civictheme/includes/social_links.inc, docroot/themes/contrib/civictheme/includes/subject_card.inc, docroot/themes/contrib/civictheme/includes/task_card.inc, docroot/themes/contrib/civictheme/includes/utilities.inc, docroot/themes/contrib/civictheme/includes/views.inc
1. Added `civictheme_field_has_value` - helper to check for field existence and has a value.
2. Updated all the places where we do this check manually.
=> [CIVIC-732] Added field existence and value check helper.

docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/webpack/assets.js
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-660
1. Excluded ajax-views from theme js builds
2. Included ajax-views via drupal library
=> [CIVIC-660] Excluded ajax-views from theme js builds

docroot/themes/contrib/civictheme/includes/accordion.inc, docroot/themes/contrib/civictheme/includes/banner.inc, docroot/themes/contrib/civictheme/includes/cards.inc, docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/includes/iframe.inc, docroot/themes/contrib/civictheme/includes/map.inc, docroot/themes/contrib/civictheme/includes/mobile_navigation.inc, docroot/themes/contrib/civictheme/includes/next_step.inc, docroot/themes/contrib/civictheme/includes/paragraphs.inc, docroot/themes/contrib/civictheme/includes/promo.inc, docroot/themes/contrib/civictheme/includes/slider.inc, docroot/themes/contrib/civictheme/includes/social_links.inc, docroot/themes/contrib/civictheme/includes/utilities.inc, docroot/themes/contrib/civictheme/includes/views.inc
CIVIC-732
1. Added a theme helper function for all entities that have theme.
2. Manually updated where we set theme with this helper
3. Consolidated where we set theme (and title) to `civictheme_preprocess_paragraph`
=>  [CIVIC-732] Added field existence and value check helper. 

docroot/themes/contrib/civictheme/includes/views.inc, tests/behat/features/paragraph.civictheme_listing.view.feature
**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-731
1. Added cache context and tags
=> [CIVIC-731] Fixed Card Theme being applied inconsistent in the Listing component

docroot/themes/contrib/civictheme/civictheme_create_subtheme.php, tests/phpunit/unit/CivicthemeCreateSubthemeScriptUnitTest.php
https://salsadigital.atlassian.net/browse/CIVIC-664
1. Stater kit theme generation script updated.
2. Added --remove-flag parameter as non positional parameter.
=> [CIVIC-664] Updated starter kit theme script to remove example component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/card-container/card-container.stories.js, docroot/themes/contrib/civictheme/theme-settings.php
https://salsadigital.atlassian.net/browse/CIVIC-956
1. Card container component storybook implementation.
=> [CIVIC-956] Added allowing to select card type in card container in Storybook.

docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_site_section.yml
https://salsadigital.atlassian.net/browse/CIVIC-695
=> [CIVIC-695] Added missing description.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/_index.scss
https://salsadigital.atlassian.net/browse/CIVIC-961
=> [CIVIC-961] Added font smoothing.

docroot/themes/contrib/civictheme/includes/form.inc, tests/behat/features/view.civictheme_listing_examples.feature
https://salsadigital.atlassian.net/browse/CIVIC-963
1. Update cache tags when new terms added.
https://nimb.ws/JFfdSN
=> [CIVIC-963] Added cache tags for exposed filters to avoid exposed block cache.

docroot/themes/contrib/civictheme/includes/link.inc, docroot/themes/contrib/civictheme/theme-settings.php
1. `Override domains` should be visible despite `Open links in a new window` is selected.
=> Fixed external links not always being replaced.

docroot/themes/contrib/civictheme/includes/link.inc, docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeHtmlLinkUnitTest.php
https://salsadigital.atlassian.net/browse/CIVIC-959
1. Fixed links processing to work with links containing CT classes.
=> [CIVIC-959] Fixed links processing to work with links containing CT classes.

docroot/themes/contrib/civictheme/civictheme.theme, docroot/themes/contrib/civictheme/includes/html.inc, tests/behat/features/content_type.civictheme_page.view.feature
https://salsadigital.atlassian.net/browse/CIVIC-975
1. Added hook_preprocess_html to add site section class
=> [CIVIC-975] Added site section class to body element.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.stories.twig, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
https://salsadigital.atlassian.net/browse/CIVIC-572
1. Fixed mobile Side Navigation menu collapsable issue.
https://nimb.ws/MvTy2c
=> [CIVIC-572] Fixed mobile Side Navigation menu collapsing on grand-parents.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss, docroot/themes/contrib/civictheme/theme-settings.php
https://salsadigital.atlassian.net/browse/CIVIC-959
1. Fixed Override domains theme settings.
2. Aligned the icon with the link.
=> [CIVIC-959] Fixed Override domains theme settings.

scripts/drevops/drupal-install-site.sh
https://salsadigital.atlassian.net/browse/CIVIC-625
1.
=> [CIVIC-625] Fixed builds failing on missing layout column plugin.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/ckeditor-content/ckeditor-content.stories.js, docroot/themes/contrib/civictheme/webpack/webpack.common.js
https://salsadigital.atlassian.net/browse/CIVIC-981
1. Added content link component.
2. Updated content-related component to use newly added content link component.
3. Added a temporary fix to resolve knobs addon from the theme root folder.
=> [CIVIC-981] Added Content link component

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.scss
=> [CIVIC-747] Updated fonts story.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-description/field-description.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-description/field-description.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-description/field-description.twig
https://salsadigital.atlassian.net/browse/CIVIC-795
1. Added field description component.
=> [CIVIC-795] Field description component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.scss
https://salsadigital.atlassian.net/browse/CIVIC-747
1. Updated font-weight to 100.
=> [CIVIC-747] Updated Thin font weight to 100.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
https://salsadigital.atlassian.net/browse/CIVIC-771
1. updated existing button component with props as per AC (add/remove props to match the list)
2. Updated states to reflect the new disabled condition opacity
=> [CIVIC-771] Updated storybook button component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.twig
https://salsadigital.atlassian.net/browse/CIVIC-810
1.
=> [CIVIC-810] Updated Checkbox components in Storybook.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_table.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.twig
https://salsadigital.atlassian.net/browse/CIVIC-786
1. Updated table component props
2. Fixed Caption styles
=> [CIVIC-786] Updated Table component.

docroot/modules/custom/civictheme_content/civictheme_content.install, docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/5c0ad15f-3e9c-4eeb-8525-7a064b06fc58.yml
https://salsadigital.atlassian.net/browse/CIVIC-990
1. Fixed missing  Corporate.civictheme.io - Default content - Social icons.
=> [CIVIC-990]  Fixed missing  Corporate.civictheme.io - Default content - Social icons.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/body-copy/body-copy.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/body-copy/body-copy.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/body-copy/body-copy.twig
https://salsadigital.atlassian.net/browse/CIVIC-768
1. Added body Copy component
=> [CIVIC-768] Added body copy component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.twig
https://salsadigital.atlassian.net/browse/CIVIC-813
1. Updated select storybook component.
=> [CIVIC-813] Updated select storybook component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textfield/textfield.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textfield/textfield.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textfield/textfield.twig
https://salsadigital.atlassian.net/browse/CIVIC-801
1. Updated textfield component
2. Used default input variables.
=> [CIVIC-801] Updated Textfield component.

.docker/Dockerfile.cli, .docker/Dockerfile.cli2, .docker/Dockerfile.php, composer.json, composer.lock, docroot/themes/contrib/civictheme/includes/utilities.inc, docroot/themes/contrib/civictheme/theme-settings.php
https://salsadigital.atlassian.net/browse/CIVIC-996
1. Updated PHP to 8.1 
2. Patched PHP 8.1: webform_css_alter warning
3. Remove the use of reset of objects in utilities.
4. Fied Deprecation warnings on the theme settings page.
=> [CIVIC-996] Updated PHP to 8.1

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
https://salsadigital.atlassian.net/browse/CIVIC-798
1. Fixed icons for errors in a storybook.
=> [CIVIC-798] Fixed icons for errors in a storybook.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo/promo.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
https://salsadigital.atlassian.net/browse/CIVIC-995
1. Fixed is-external and right-arrow icons.
=> [CIVIC-995] Fixed is-external and right-arrow icons.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.stories.js
https://salsadigital.atlassian.net/browse/CIVIC-786
1. Default value fix
=> [CIVIC-786] Fixed default value for Table component in Storybook.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.scss
https://salsadigital.atlassian.net/browse/CIVIC-804
1.
=> [CIVIC-804] Minimum width and border radius.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_icon.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.scss
https://salsadigital.atlassian.net/browse/CIVIC-998
1. Updated icon scss to handle theme style color.
https://nimb.ws/fARJcq
=> [CIVIC-998] Updated icon scss to handle theme style color.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.twig
https://salsadigital.atlassian.net/browse/CIVIC-813
1. Updated storybook select component.
=> [CIVIC-813] Updated storybook select component.

docroot/themes/contrib/civictheme/includes/local_tasks.inc
https://salsadigital.atlassian.net/browse/CIVIC-1001
1.
=> [CIVIC-1001] Fix tab order.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.twig
https://salsadigital.atlassian.net/browse/CIVIC-983
1. Updated content link component for accessibility
=> [CIVIC-983] Updated content link component for accessibility.

docroot/themes/contrib/civictheme/includes/link.inc, docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeHtmlLinkUnitTest.php, tests/behat/features/links.feature
https://salsadigital.atlassian.net/browse/CIVIC-1007
Closes https://github.com/salsadigitalauorg/civictheme_source/issues/643
1. Added more checks for the format of the URL + tests.
=> [CIVIC-1007] Fixed invalid URLs triggering errors when parsing external links.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig
https://salsadigital.atlassian.net/browse/CIVIC-885
1. Removed the Share link altogether - we do not have such functionality.
2. Replaced the View transcript link with a Tertiary button with an icon.
=> [CIVIC-885] Updated video player story book component.

composer.json, composer.lock, docroot/modules/custom/cs_core/cs_core.info.yml
https://salsadigital.atlassian.net/browse/CIVIC-787
1. Added styleguide module
2. Added to cs_core module dependencies.
=> [CIVIC-787] Part-1: Added styleguide module.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig
https://salsadigital.atlassian.net/browse/CIVIC-774
1.
=> [CIVIC-774] Updated radio chip dismiss icon.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.twig
https://salsadigital.atlassian.net/browse/CIVIC-825
1.  Updated the back-to-top component.
=> [CIVIC-825] Updated the back to top component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/skip-link/skip-link.scss
https://salsadigital.atlassian.net/browse/CIVIC-879
1.  Fixed Colors and padding for skip link.
=> [CIVIC-879] Updated skip link storybook component.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
https://salsadigital.atlassian.net/browse/CIVIC-783
1. Implemented Is disabled prop.
2. Removed Underline for focus and hover.
=> [CIVIC-783] Updated civic theme link component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/directional-link/directional-link.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
https://salsadigital.atlassian.net/browse/CIVIC-867
1. Pagination component.
2. Used Field label and Select component for items per page
3. Direction links styles are from the component itself.
=> [CIVIC-867] Updated pagination component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/typography.stories.twig
https://salsadigital.atlassian.net/browse/CIVIC-780
1. Minor list text change.
=> [CIVIC-780] External link fix.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
https://salsadigital.atlassian.net/browse/CIVIC-1008
1. Updated Promo and promo card component to handle external link
2. Fixed missing demo image 4.
=> [CIVIC-1008] Fixed external link icon added when 'is external' option is unchecked.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.twig
https://salsadigital.atlassian.net/browse/CIVIC-891
1. Quote component
=> [CIVIC-891] Added Quote component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.twig
https://salsadigital.atlassian.net/browse/CIVIC-1004
1. Added popover component.
=> [CIVIC-1004] Added Popover component.

docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_blend_mode.yml, docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_blend_mode.yml, docroot/themes/contrib/civictheme/includes/banner.inc
https://salsadigital.atlassian.net/browse/CIVIC-1019
1. Implemented blend mode per-page.
2. Implemented logic to only applies if the banner image was set as an override per-page.
=> [CIVIC-1019] Implemented blend mode per-page.

docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/menu_link_content/d43ff5d5-9a9d-49a4-9dd0-6656c4c16a61.yml, docroot/modules/custom/civictheme_content/src/Helper.php, docroot/themes/contrib/civictheme/theme-settings.provision.inc, scripts/custom/drupal-install-site-3-provision-content.sh, tests/behat/features/menu.feature
https://salsadigital.atlassian.net/browse/CIVIC-1026
1. Changed the order of provisioning to provision after default content, as default content does not adjust for the current theme.
=> [CIVIC-1026] Added a test for provisioning of thew mobile navigation.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.stories.js
https://salsadigital.atlassian.net/browse/CIVIC-939
1. Updated table of content storybook component.
=> [CIVIC-939] Updated table of content storybook component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.scss
https://salsadigital.atlassian.net/browse/CIVIC-891
1. Updated typography font size as per figma.
=> [CIVIC-891] Quote typography fix.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.js
https://salsadigital.atlassian.net/browse/CIVIC-1004
1. Border radius and js error fix.
=> [CIVIC-1004] Border radius fix.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.twig
https://salsadigital.atlassian.net/browse/CIVIC-884
1. Accessibility 
2. Design
3. Js refactor
=> [CIVIC-884] Updated tooltip design and accessibility.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
https://salsadigital.atlassian.net/browse/CIVIC-867
1.
=> [CIVIC-867] Updated Pagination design and added accessibility title.

docroot/themes/contrib/civictheme/civictheme_library/components/04-templates/page/page.twig
1. Removed the rogue class layout-container.
=> [CIVIC-984] Removed the rogue class layout-container.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
https://salsadigital.atlassian.net/browse/CIVIC-942
1. Updated slider storybook component.
=> [CIVIC-942] Updated slider storybook component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.twig
https://salsadigital.atlassian.net/browse/CIVIC-948
1. Changed demo icons to ones currently available. YouTube and Dropbox are not present in the icons folder and I can't export from Figma because the file is locked for editing.
2. Updated styles to match Storybook.
3. Added mobile styles.
=> [CIVIC-948] Updated social links styles and attributes in Storybook.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.scss
https://salsadigital.atlassian.net/browse/CIVIC-939
1. Updated typography.
2. Fixed mobile toc width
=> [CIVIC-939] Updated toc component.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/paragraph/paragraph.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/paragraph/paragraph.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/paragraph/paragraph.twig
https://salsadigital.atlassian.net/browse/CIVIC-1041
1. Renamed Body copy to Paragraph.
=> [CIVIC-1041] Renamed Body copy to paragraph.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/secondary-navigation/secondary-navigation.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.scss, docroot/themes/contrib/civictheme/civictheme_starter_kit/components/03-organisms/header/header.twig, docroot/themes/contrib/civictheme/civictheme_starter_kit/components/variables.base.scss, docroot/themes/contrib/civictheme/civictheme_starter_kit/components/variables.components.scss
https://salsadigital.atlassian.net/browse/CIVIC-1037
https://salsadigital.atlassian.net/browse/CIVIC-1045
https://salsadigital.atlassian.net/browse/CIVIC-1044
https://salsadigital.atlassian.net/browse/CIVIC-1039
https://salsadigital.atlassian.net/browse/CIVIC-1043
=> [CIVIC-1037, CIVIC-1039, CIVIC-1043, CIVIC-1044, CIVIC-1045] Fixed several colour issues.

docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_automated_list.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_automated_list.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_component_block.field_c_b_components.yml, docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_components_bott.yml, docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_components.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_column_count.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_content.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_fill_width.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_link_above.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_link_below.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_type.yml, docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_automated_list.yml, docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_social_icon.yml, docroot/themes/contrib/civictheme/config/install/views.view.civictheme_automated_list.yml, tests/behat/features/paragraph.civictheme_automated_list.fields.feature
https://salsadigital.atlassian.net/browse/CIVIC-1048
1. Added new fields.
2. Updated labels of existing fields.
=> [CIVIC-1048] Update Automated List fields.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.twig
https://salsadigital.atlassian.net/browse/CIVIC-1049
1. Added a new component Item Grid to storybook.
=> [CIVIC-1049] Added a new component Item Grid to storybook.

docroot/modules/custom/civictheme_styleguide/components/callout.inc
https://salsadigital.atlassian.net/browse/CIVIC-901
1. Callout style guide integration.
=> [CIVIC-901] Callout component Styleguide integration.

docroot/themes/contrib/civictheme/assets/js/civictheme-ajax-views.js, docroot/themes/contrib/civictheme/civictheme.theme, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/single-filter/single-filter.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/single-filter/single-filter.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/single-filter/single-filter.twig, docroot/themes/contrib/civictheme/includes/filter.inc, docroot/themes/contrib/civictheme/includes/form.inc, docroot/themes/contrib/civictheme/includes/views.inc, docroot/themes/contrib/civictheme/templates/form/checkboxes--civictheme-basic-filter.html.twig, docroot/themes/contrib/civictheme/templates/form/form-element--civictheme-filter-chip.html.twig, docroot/themes/contrib/civictheme/templates/form/radios--civictheme-basic-filter.html.twig
https://salsadigital.atlassian.net/browse/CIVIC-1041
1.
=> [CIVIC-1041] Renamed Basic filter to Single filter.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.twig
https://salsadigital.atlassian.net/browse/CIVIC-852
1. Updated service card to use Content link component. (As per figma)
=> [CIVIC-852] Updated service card to use Content link component.

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
https://salsadigital.atlassian.net/browse/CIVIC-924
1. Updated icon colors, Only used for light theme.
2. Updated spacing for message component.
=> [CIVIC-924] Updated message storybook component.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig
https://salsadigital.atlassian.net/browse/CIVIC-1085
1. Updated footer story book component.
=> [CIVIC-1085] Updated footer story book component.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.twig
https://salsadigital.atlassian.net/browse/CIVIC-938
1. Implemented Skip to content for side navigation.
=> [CIVIC-938] Implemented Skip to content for side navigation.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
https://salsadigital.atlassian.net/browse/CIVIC-921
1. Fixed alert dark colors.
=> [CIVIC-921] Fixed alert dark colors.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
https://salsadigital.atlassian.net/browse/CIVIC-841
1. Updated event card logo.
=> [CIVIC-841] Updated event card logo.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-close.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
https://salsadigital.atlassian.net/browse/CIVIC-927
1. Fixed mobile navigation icons and missing parent item.
=> [CIVIC-927] Fixed mobile navigation icons and missing parent item.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
https://salsadigital.atlassian.net/browse/CIVIC-843
1. Fixed design
=> [CIVIC-843] Fixed navigation card styles.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/callout/callout.twig, docroot/themes/contrib/civictheme/includes/callout.inc
https://salsadigital.atlassian.net/browse/CIVIC-1040
1.
=> [CIVIC-1040] Fixed callout component button rendering.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig
https://salsadigital.atlassian.net/browse/CIVIC-855
1.
=> [CIVIC-855] Fixed Subject card styles.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/layout/layout.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
https://salsadigital.atlassian.net/browse/CIVIC-1077
1.
=> [CIVIC-1077] Fixed TOC width on mobile.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig, tests/behat/features/pagination.view.feature
https://salsadigital.atlassian.net/browse/CIVIC-1070
1.
=> [CIVIC-1070] Updated pager component, fixed link styles.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.scss
https://salsadigital.atlassian.net/browse/CIVIC-1081
1.
=> [CIVIC-1081] Fixed Quote component design.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig, docroot/themes/contrib/civictheme/includes/slider.inc, docroot/themes/contrib/civictheme/templates/misc/slider-slide-tags.html.twig
https://salsadigital.atlassian.net/browse/CIVIC-1101
1. Updated template as per Figma.
2. Added date for event content reference.
=> [CIVIC-1101] Fixed Slider component design and integration.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.scss
https://salsadigital.atlassian.net/browse/CIVIC-1092
1.
=> [CIVIC-1092] Breadcrumb title fix.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss
https://salsadigital.atlassian.net/browse/CIVIC-1069
1.
=> [CIVIC-1069] Fixed menu external link design.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.stories.js
https://salsadigital.atlassian.net/browse/CIVIC-918
1. Fixed Group filters
2. Fixed pagination design and props
=> [CIVIC-918] Fixed list component properties.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss
=> [CIVIC] Fix typo on slider.

docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
1. Yml key that was breaking the build
=> Updated default content yml.

docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeColorUtilityUnitTest.php, docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeUtilityUnitTest.php
https://salsadigital.atlassian.net/browse/CIVIC-1119
1. Added unit test for color classes.
=> [CIVIC-1119] Added unit test for color classes.

docroot/themes/contrib/civictheme/includes/views.inc
https://salsadigital.atlassian.net/browse/CIVIC-1122
1. Fixed automated list pages 500 error.
=> [CIVIC-1122] Fixed automated list pages 500 error.

docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/0ba446a2-c1ce-4c8e-a20d-0d9ae5949aca.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/1accbc91-68c8-4a86-a973-b7120ce05c9c.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/2cb01445-7f3f-4aca-9451-6d26a6032100.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/4d273ca8-0889-4e43-8edd-73fcb4ed8340.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/5750f380-5fb2-484a-8f78-9e1fa1749c32.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/583e8b18-8156-415c-a80e-4dbf564d5f99.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/5a7cc060-cdf5-4097-8dce-15a0c7270f98.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/60ac1244-9ada-43d3-a534-4e54086cc29e.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/78160c95-cb6d-4321-9aba-2118aff8fc59.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/91452662-e67a-4c74-aabc-bf37d25d43d8.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/a0539fd0-ef51-47c9-a47b-e08199052f1e.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/afb3e47d-409f-47c9-b5cc-0bbb00531e19.yml
1. Fixed missing plain text plugin error logs.
=> Fixed missing plain text plugin error logs.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/_index.scss
https://salsadigital.atlassian.net/browse/CIVIC-1017
1. Fixed mixed level symbols issue.
=> [CIVIC-1017] Fixed mixed level symbols issue.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.scss, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_accordion_panel.field_c_p_title.yml, tests/behat/features/paragraph.civictheme_accordion.fields.feature
https://salsadigital.atlassian.net/browse/CIVIC-1083
=> [CIVIC-1083] Fixed accordion background color and title not being required.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.stories.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig, tests/behat/features/paragraph.civictheme_slider.view.feature
https://salsadigital.atlassian.net/browse/CIVIC-942
1. Updated slider theme component.
=> [CIVIC-942] Updated slider theme component.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
https://salsadigital.atlassian.net/browse/CIVIC-1149
1. Updated banner title content wrap to be full width if no featured image.
=> [CIVIC-1149] Updated banner title content wrap component.

docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_navigation_card.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_navigation_card.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_show_image_as_icon.yml, docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_show_image_as_icon.yml, docroot/themes/contrib/civictheme/includes/navigation_card.inc, tests/behat/features/paragraph.civictheme_navigation_card.fields.feature
https://salsadigital.atlassian.net/browse/CIVIC-1153
1. Updated navigation image component to be shown as icon.
=> [CIVIC-1153] Updated navigation image component to be shown as icon.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml, docroot/themes/contrib/civictheme/includes/cards.inc
https://salsadigital.atlassian.net/browse/CIVIC-1152
1. Updated events content type display components.
=> [CIVIC-1152] Updated events content type display components.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.stories.js
https://salsadigital.atlassian.net/browse/CIVIC-1150
1. Updated toc component styles.
=> [CIVIC-1150] Updated toc component styles.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.twig, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
https://salsadigital.atlassian.net/browse/CIVIC-1138
1. Updated the following components to use CSS variables:
1. search
2. service-card
3. subject-card
4. table-of-contents
5. tabs
6. tooltip
=> [CIVIC-1138] Converted components to use CSS variables. Part 1.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
https://salsadigital.atlassian.net/browse/CIVIC-1153
1. Updated Image (icon) size to use large same as icon.
=> [CIVIC-1153] Updated Image size to use large same as icon.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/layout/layout.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
https://salsadigital.atlassian.net/browse/CIVIC-1138
1. Updated the following components to use CSS variables:
- Collapsible
- Layout
=> [CIVIC-1138] Converted components to use CSS variables.

docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_government/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_government/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml, docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml, docroot/themes/contrib/civictheme/theme-settings.provision.inc
https://salsadigital.atlassian.net/browse/CIVIC-1147
1. Updated footer block content text styles.
=> [CIVIC-1147] Updated footer block content text styles.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
https://salsadigital.atlassian.net/browse/CIVIC-1136
1. Updated alert icon to be inline with alert title.
=> [CIVIC-1136] Updated alert icon to be inline with alert title.

docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_event_card.field_c_p_summary.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_summary.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_promo.field_c_p_summary.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_promo_card.field_c_p_summary.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_publication_card.field_c_p_summary.yml
https://salsadigital.atlassian.net/browse/CIVIC-1241
1. Updated help text for Summary fields of cards.
=> [CIVIC-1241] Updated help text for Summary fields of cards.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/flyout/flyout.js, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
https://salsadigital.atlassian.net/browse/CIVIC-1245
1. Fixed Flout component
=> [CIVIC-1245] Fix A11Y issue Flyout component.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js
https://salsadigital.atlassian.net/browse/CIVIC-1249
1. Enable the focus js changes.
2. Fix the up key issue.
=> [CIVIC-1249] Fixed collapsible focus issue.

docroot/themes/contrib/civictheme/includes/banner.inc
=> [CIVIC] Fixed banner typo.

docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/8f45163f-252f-46e3-b3d3-7930b1d9b6c7.yml, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_subject_card.field_c_p_image.yml, tests/behat/features/paragraph.civictheme_subject_card.fields.feature
https://salsadigital.atlassian.net/browse/CIVIC-1286
1. Updated subject card component.
=> [CIVIC-1286] Updated Subject card to not require image and fixed arrow.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.scss
https://salsadigital.atlassian.net/browse/CIVIC-1284
1. Updated promo button size ito be based on text length.
=> [CIVIC-1284] Updated promo button size ito be based on text length.

docroot/themes/contrib/civictheme/civictheme.info.yml, docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_slider_slide_ref.default.yml, docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_slider_slide_ref.default.yml, docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_slider_slide_ref.field_c_p_link_text.yml, docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_link_text.yml, docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_slider_slide_ref.yml, docroot/themes/contrib/civictheme/includes/slider.inc, tests/behat/features/paragraph.civictheme_slider.fields.feature, tests/behat/features/paragraph.civictheme_slider.render.feature
https://salsadigital.atlassian.net/browse/CIVIC-1292
1. Updated reference slider component to have a custom button link.
2. Updated behat test.
=> [CIVIC-1292] Updated reference slider component to have a custom button link.

docroot/themes/contrib/civictheme/includes/link.inc, docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
https://salsadigital.atlassian.net/browse/CIVIC-1291
Closes https://github.com/salsadigitalauorg/civictheme_source/issues/773
1. Updated content Link processing to process all links.
2. Updated Unit test.
=> [CIVIC-1291] Updated content Link processing to process all links.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
https://salsadigital.atlassian.net/browse/CIVIC-1288
1. Removed the unused icon usage.
=> [CIVIC-1288] Removed the unused icon usage.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
https://salsadigital.atlassian.net/browse/CIVIC-1034
1. Fixed Field label - Storybook : font-size as per Figma.
=> [CIVIC-1034] Fixed Field label - Storybook : font-size as per Figma.

composer.json, composer.lock, tests/behat/features/theme.settings.vertical_tabs.feature
https://salsadigital.atlassian.net/browse/CIVIC-1312
1. Re-applied vertical tabs patch
2. Added behat test.
=> [CIVIC-1312] Applied vertical tabs patch.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
https://salsadigital.atlassian.net/browse/CIVIC-1257
1. Updated menu to communicate the state: A11Y
=> [CIVIC-1257] Updated menu to communicate the state: A11Y

docroot/themes/contrib/civictheme/config/install/user.role.civictheme_site_administrator.yml, tests/behat/features/roles.civictheme_site_administrator.feature
https://salsadigital.atlassian.net/browse/CIVIC-1305
1. Site Administrator role permissions change.
=> [CIVIC-1305] Site administrator user permissions change.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.twig, tests/behat/features/migrate.feature
https://salsadigital.atlassian.net/browse/CIVIC-1268
1. Updated title to use heading and no div wrap.
=> [CIVIC-1268] Updated title to use heading and no div wrap.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
https://salsadigital.atlassian.net/browse/CIVIC-1323
1. Updated card headings to remove overrides.
=> [CIVIC-1323] Updated card headings to remove overrides.

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig, docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
https://salsadigital.atlassian.net/browse/CIVIC-1257
1. Updated mobile menu to communicate the state.
=> [CIVIC-1257] Updated mobile menu to communicate the state: A11Y

docroot/themes/contrib/civictheme/theme-settings/civictheme.theme-settings.colors.js
=> [#910] Fixed type in Brand selector checkbox.

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
https://salsadigital.atlassian.net/browse/CIVIC-1296
1. Fixed toc jumping issue when clicked.
https://nimb.ws/2b1iml
=> [CIVIC-1296] Fixed toc jumping issue when clicked.

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss, docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_highlight.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/callout/callout.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.scss, docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.scss
https://salsadigital.atlassian.net/browse/CIVIC-1311
1. Fixed stripe variable
2. Fixed icon colours in Message and Alert components.
=> [CIVIC-1311] Fixed stripe variables and Message and Alerts icon colours.

.circleci/config.yml, .docker/Dockerfile.cli.sibling, docroot/themes/contrib/civictheme/civictheme_library/webpack/info.js, scripts/drevops/lint.sh, tests/bats/assets.bats, tests/bats/assets_library.bats
=> [#1038] Fixed path resolution in info.js to work correctly in sub-theme.  @AlexSkrypnyk

docroot/themes/contrib/civictheme/includes/link.inc, docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
closes #963 
1. Fixed pattern
2. Added unit tests
=> [CIVIC-1372] Fixed email extraction pattern.

docroot/modules/custom/civictheme_migrate/assets/migration_schemas/block_civictheme_block.json, docroot/modules/custom/civictheme_migrate/assets/migration_schemas/block_content_civictheme_component_block.json, docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.block_civictheme.yml, docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.block_content_civictheme_component_block copy.yml, docroot/modules/custom/civictheme_migrate/src/ContentComponentFactory.php, docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/BlockPluginId.php, docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/BlockTheme.php, docroot/modules/custom/civictheme_migrate/src/Utils/CivicthemeTrait.php, tests/behat/bootstrap/FeatureContext.php, tests/behat/features/migrate.mappings.components.promo.feature, tests/behat/fixtures/migrate/civictheme_migrate.block_civictheme.json, tests/behat/fixtures/migrate/civictheme_migrate.block_content_civictheme_component_block.json, tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_5.json, tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_6.json
https://salsadigital.atlassian.net/browse/CIVIC-1362
1. Promo component
2. Page migration with promo
3. Block migration with promo
4. Added a custom process plugin for block migrations.
=> [CIVIC-1362] Migrations mapping - Promo component

docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.media_civictheme_image.yml, tests/behat/features/migrate.mappings.civictheme_image.feature, tests/behat/fixtures/migrate/civictheme_migrate.media_civictheme_image_1.json
https://salsadigital.atlassian.net/browse/CIVIC-1446
1. Alt tag character limit.
=> [CIVIC-1446] Updated image alt tag process.

composer.lock
- symfony/http-foundation updated from v6.3.6 to v6.3.7 patch See changes: https://github.com/symfony/http-foundation/compare/v6.3.6...v6.3.7 Release notes: https://github.com/symfony/http-foundation/releases/tag/v6.3.7
- symfony/http-kernel updated from v6.3.6 to v6.3.7 patch See changes: https://github.com/symfony/http-kernel/compare/v6.3.6...v6.3.7 Release notes: https://github.com/symfony/http-kernel/releases/tag/v6.3.7
- symfony/yaml updated from v6.3.3 to v6.3.7 patch See changes: https://github.com/symfony/yaml/compare/v6.3.3...v6.3.7 Release notes: https://github.com/symfony/yaml/releases/tag/v6.3.7
- symfony/translation updated from v6.3.6 to v6.3.7 patch See changes: https://github.com/symfony/translation/compare/v6.3.6...v6.3.7 Release notes: …
=> Updated dependencies.

web/themes/contrib/civictheme/civictheme_create_subtheme.php
https://www.drupal.org/project/civictheme/issues/3398934
closes #1138 1138
=> Issue #3398934 by amjad1233, alex.skrypnyk: Undefined array key error when specifying path in CivicTheme subtheme creation script.

web/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.js
=> [CIVIC-1342] Fixed TOC header tag.

tests/behat/features/view.civictheme_automated_list_examples.feature
=> Fixed views filtering test.

web/modules/custom/civictheme_govcms/src/CivicthemeGovcmsManager.php, web/modules/custom/cs_generated_content/generated_content/user/user.inc, web/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_content-link.scss, web/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_form.scss, web/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_link.scss, web/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_visibility.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.js, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/input/input.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/radio/radio.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.scss, web/themes/contrib/civictheme/civictheme_library/components/01-atoms/textfield/textfield.scss, web/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.scss, web/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss, web/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss, web/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.scss, web/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.scss, web/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss, web/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.scss, web/themes/contrib/civictheme/theme-settings.provision.inc
=> [CIVIC-1456] Fixed links and menu items showing focus outline when activated by a mouse.

.circleci/config.yml, web/themes/contrib/civictheme/includes/link.inc, web/themes/contrib/civictheme/phpstan.neon
=> Added buildiung for legacy Drupal version.

composer.lock, tests/behat/bootstrap/FeatureContext.php
```
- drupal/rat removed (installed version was 1.0.0)
- drupal/core-composer-scaffold updated from 10.1.6 to 10.1.8 patch
See changes: https://github.com/drupal/core-composer-scaffold/compare/10.1.6...10.1.8
Release notes: https://github.com/drupal/core-composer-scaffold/releases/tag/10.1.8
- symfony/polyfill-php80 updated from v1.28.0 to v1.29.0 minor
See changes: https://github.com/symfony/polyfill-php80/compare/v1.28.0...v1.29.0
Release notes: https://github.com/symfony/polyfill-php80/releases/tag/v1.29.0
- symfony/http-foundation updated from v6.3.11 to v6.3.12 patch
See changes: https://github.com/symfony/http-foundation/compare/v6.3.11...v6.3.12
Release notes: https://github.com/symfony/http-foundation/releases/tag/v6.3.12
- symfony/event-dispatcher updated from …
```
=> Updated Composer deps.

web/themes/contrib/civictheme/includes/form.inc, web/themes/contrib/civictheme/templates/form/checkboxes.html.twig, web/themes/contrib/civictheme/templates/form/radios.html.twig
=> Fixed checkboxes and radios element display.

tests/behat/bootstrap/FeatureContext.php, tests/behat/features/publishing_workflow.feature
1. Added behat test for civictheme_page Publishing workflow.
1. Added Behat test for other content type.
=> [#3415754] Added behat test.

docs/development.md, docs/testing.md, scripts/custom/provision-30-enable-modules.sh
1. Updated testing Docs to use 'ahoy provision'.
=> Updated testing Docs to use 'ahoy provision'.

.docker/cli.dockerfile, .docker/cli.sibling.dockerfile, scripts/custom/provision-20-activate-subtheme.sh, tests/bats/assets.subtheme.custom.bats, tests/bats/assets.subtheme.sibling.bats
https://salsadigital.atlassian.net/browse/CIVIC-1052
1. Updated provision-20-activate-subtheme.sh script and added the flag --remove-examples.
=> [CIVIC-1052] Updated provision-20-activate-subtheme.sh script and added the flag --remove-examples.

web/themes/contrib/civictheme/civictheme.info.yml, web/themes/contrib/civictheme/civictheme_starter_kit/civictheme_starter_kit.info.yml, web/themes/contrib/civictheme/civictheme_starter_kit/webpack/webpack.common.js, web/themes/contrib/civictheme/webpack/webpack.common.js
https://www.drupal.org/project/civictheme/issues/3427321
1. Removed pages & ct-pages component references.
=> Issue #3427321 by joshua1234511: Missing directory "05-pages"

web/themes/contrib/civictheme/civictheme.info.yml, web/themes/contrib/civictheme/civictheme_starter_kit/civictheme_starter_kit.info.yml, web/themes/contrib/civictheme/templates/layout/page.html.twig
https://www.drupal.org/project/civictheme/issues/3415685
1. Added `hidden` region at the bottom of the theme with a UI Kit class 'ct-visually-hidden'.
2. Updated stater-kit to include the new region.
=> Issue #3415685 by joshua1234511: Add a hidden region for entity references to civictheme.info.yml

web/themes/contrib/civictheme/includes/mobile_navigation.inc
https://salsadigital.atlassian.net/browse/CIVIC-1725
JIRA ONLY
1.
=> [CIVIC-1725] Added fix for Mobile navigation does not expand sub-links automatically.

web/themes/contrib/civictheme/theme-settings.provision.inc
https://www.drupal.org/project/civictheme/issues/3441209
1. Updated code with provided working solution from https://git.drupalcode.org/project/civictheme/-/merge_requests/6/diffs
=> Issue #3441209 by joshua1234511, sonnykt: Theme content provisioning creates invalid config views.view.civictheme_media

web/themes/contrib/civictheme/assets/sass/moderation_controls/_moderation_controls.scss, web/themes/contrib/civictheme/assets/sass/theme.scss
1. Updated styling for the moderation controls.
=> Updated styling for the moderation controls.

web/themes/contrib/civictheme/includes/local_tasks.inc
1. Fixed Active tab to be marked as such in Drupal.
=> Fixed Active tab to be marked as such in Drupal.

web/themes/contrib/civictheme/assets/sass/layout_builder/_layout_builder.scss, web/themes/contrib/civictheme/assets/sass/theme.scss
1. Added styles on the Layout Builder admin page
=> Added styles on the Layout Builder admin page

tests/bats/assets.basetheme.bats, web/themes/contrib/civictheme/assets/sass/theme.admin.scss, web/themes/contrib/civictheme/assets/sass/theme.scss, web/themes/contrib/civictheme/civictheme.libraries.yml, web/themes/contrib/civictheme/civictheme.theme, web/themes/contrib/civictheme/webpack/admin_css.js, web/themes/contrib/civictheme/webpack/webpack.common.js
This is required to make the layout builder and moderation control styles to be available to the sub-themes.
=> Moved admin styles into separate library.

web/themes/contrib/civictheme/tests/src/Unit/CivicthemeColorUtilityUnitTest.php, web/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php, web/themes/contrib/civictheme/tests/src/Unit/CivicthemeUtilityUnitTest.php
https://www.drupal.org/node/3455169
=> Issue #3455169: Automated Drupal 11 compatibility fixes for civictheme.

web/themes/contrib/civictheme/README.md, web/themes/contrib/civictheme/package-lock.json, web/themes/contrib/civictheme/package.json
https://github.com/civictheme/uikit/releases/tag/v1.8.0
=> Updated to UIKit 1.8.

web/themes/contrib/civictheme/includes/automated_list.inc
https://www.drupal.org/project/civictheme/issues/3454548
=> Issue #3454548 by alex.skrypnyk, abhishek_gupta1, ivrh, thisisalistairsaccount: Automated list from Banner bottom components throws error.

package-lock.json, package.json, web/modules/custom/civictheme_dev/civictheme_dev.install, web/modules/custom/civictheme_dev/civictheme_dev.post_update.php, web/themes/contrib/civictheme/civictheme.layouts.yml, web/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml, web/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml, web/themes/contrib/civictheme/config/schema/civictheme.schema.yml, web/themes/contrib/civictheme/includes/page.inc, web/themes/contrib/civictheme/package-lock.json, web/themes/contrib/civictheme/src/Plugin/Layout/ThreeColumnsLayout.php, web/themes/contrib/civictheme/templates/layout/layout--single-column-contained.html.twig, web/themes/contrib/civictheme/templates/layout/layout--single-column.html.twig, web/themes/contrib/civictheme/templates/layout/layout--three-columns.html.twig
=> Fixed layout containment and added an option to select if the LB layout should be contained.

README.md, web/themes/contrib/civictheme/README.md
1. Shortened main README for clarity.
2. Updated Drupal theme README to point to docs because that includes information about applying the necessary core patch.
N/A
=> Update README to point to docs for theme install.

web/themes/contrib/civictheme/civictheme.post_update.php
https://www.drupal.org/project/civictheme/issues/3458260
1. Updated blocks from 'sidebar' region to 'sidebar_top_left'.
2. Enabled "3 column" layout for the Page content type.
=> Issue #3458260 by alex.skrypnyk, joshua1234511: Missing update hooks in 1.8

web/themes/contrib/civictheme/composer.dev.json
1. Added tbachert/spi to allow-plugins.
=> Added tbachert/spi to allow-plugins.

web/themes/contrib/civictheme/assets/sass/layout_builder/_layout_builder.scss, web/themes/contrib/civictheme/includes/layout.inc, web/themes/contrib/civictheme/templates/misc/links.html.twig
https://www.drupal.org/project/civictheme/issues/3415664
1. Template override added.
https://share.nmblc.cloud/99db990b
https://github.com/user-attachments/assets/4440061f-d54c-44c2-8a14-992de3b4c6b0
=> Issue #3415664 by sime, joshua1234511, richardgaunt, alexskrypnyk, fionamorrison23: Contextual links are broken

web/themes/contrib/civictheme/includes/menu.inc
- https://github.com/civictheme/uikit/issues/380
1. Added navigation name to support aria-label for <nav> element
Please update the package.json file with 
```
"@civictheme/uikit": "github:civictheme/uikit#feature/CIVIC-1961-nav-element"
```
for testing.
=> [#380] Added navigation name to support aria-label for <nav> element

web/themes/contrib/civictheme/package-lock.json, web/themes/contrib/civictheme/package.json
1. Updated tags for development
=> Updated tags for development.

web/themes/contrib/civictheme/package-lock.json
=> Bump uikit.

web/themes/contrib/civictheme/build.js, web/themes/contrib/civictheme/civictheme_starter_kit/build.js
1. Synced build script with uikit
=> Updated to sync with uikit.

.docker/cli.dockerfile, .docker/cli.onlytheme.dockerfile, .docker/cli.sibling.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile, scripts/custom/provision-20-activate-subtheme.sh
=> Bump lagoon container version.

tests/behat/features/paragraph.civictheme_slider.render.feature
1. Fixing event slider test that is failing once per run.
=> Fixed slider reference test.

tests/behat/features/paragraph.civictheme_automated_list.render.feature
1. Updated automated list test to fix failures.
=> Updated automated list test css selector.

composer.json, composer.lock, web/sites/default/settings.php
1. Added contrib module to override D11 database requirements
2. Added to settings file to override database requirements - only required for servers on platform.
=> Added mysql57 module for platform restriction bypass.

web/themes/contrib/civictheme/civictheme_starter_kit/package-lock.json, web/themes/contrib/civictheme/civictheme_starter_kit/package.json, web/themes/contrib/civictheme/package-lock.json, web/themes/contrib/civictheme/package.json
1. Added supported CPU / OS options to package.json.
2. Re-run the package-lock.
3. Tested on Ubuntu 24.04 and macOS 15.3.1
=> Fix mac M1 and sass-embedded package error.

web/themes/contrib/civictheme/build.js, web/themes/contrib/civictheme/civictheme_starter_kit/build.js
1. Ensure the successReporter is used for consistency on all tasks.
=> Issue #3505934 by richardgaunt, fionamorrison23, danielgry, alan.cole, alex.skrypnyk: Updated build logging to be consistent.

scripts/custom/provision-30-enable-modules.sh
1. Added cache clear to when demo site is enabled so component namespaces are discovered.
=> Added cache clear to deploy.

composer.json, composer.lock
=> Updated Styleguide module.

phpcs.xml, web/themes/contrib/civictheme/.storybook/preview.js, web/themes/contrib/civictheme/build.js, web/themes/contrib/civictheme/civictheme.post_update.php, web/themes/contrib/civictheme/civictheme_create_subtheme.php, web/themes/contrib/civictheme/civictheme_starter_kit/.storybook/preview.js, web/themes/contrib/civictheme/includes/automated_list.inc, web/themes/contrib/civictheme/includes/banner.inc, web/themes/contrib/civictheme/includes/form_element.inc, web/themes/contrib/civictheme/includes/page.inc, web/themes/contrib/civictheme/includes/paragraphs.inc, web/themes/contrib/civictheme/includes/utilities.inc, web/themes/contrib/civictheme/phpcs.xml, web/themes/contrib/civictheme/src/CivicthemeColorManager.php, web/themes/contrib/civictheme/src/CivicthemePluginLoader.php, web/themes/contrib/civictheme/src/CivicthemeUpdateHelper.php, web/themes/contrib/civictheme/src/Drush/Commands/CivicthemeCommands.php, web/themes/contrib/civictheme/src/Plugin/Layout/ThreeColumnsLayout.php, web/themes/contrib/civictheme/tests/src/Kernel/CivicthemeMediaUtilityKernelTest.php, web/themes/contrib/civictheme/theme-settings.provision.inc
1. Added back linting.
2. Added back to linting civictheme from root directory `phpcs.xml`
=> [#3520413] Fixed lint errors

web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_limit.yml, web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_limit_type.yml
https://salsadigital.atlassian.net/browse/CIVIC-2095
1. Updated field descriptions for Limit fields (Limit and Limit type) on Automated list.
=> [#3508583] Updated field descriptions for Limit fields on Automated list.
