docroot/themes/contrib/civic/civic-library/components/01-atoms/button/button.stories.js
docroot/themes/contrib/civic/civic-library/components/01-atoms/button/button.twig

**Issue URL:**
1.  Set the button icon size parameter to use the icon_size variable instead of the button's own size variable. If an icon_size is not set for the button, the icon size matches the button size.
2. Fixed documentation in button variables for icon size.
Changed "Default" back to "None" after screenshotting.

Added support for icon size on buttons that is different to button size.

---

docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/content/content-layout--single-column-contained.twig
docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/content/content.twig

**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-610
1.  Added xxs column classes anywhere columns are normally added.
2. Made content align to layout and stretch appropriately to grid.
**Before**
Content was misaligned and did not stretch correctly to layout
**After**
Content aligns neatly and stretched appropriately to width of layout. Content conforms to 320px mobile grid.

[ONI-610] Fixed mobile layout and alignment.

---

docroot/themes/contrib/civictheme/civictheme-library/components/00-base/responsive/responsive.js

**Background**
Added fallback for mobile safari <13 which does not have addEventListener

Add support for safari 13.

---

docroot/themes/contrib/civictheme/civictheme.info.yml
docroot/themes/contrib/civictheme/config/install/views.view.civictheme_listing.yml
docroot/themes/contrib/civictheme/config/install/views.view.civictheme_listing_examples.yml
docroot/themes/contrib/civictheme/config/install/views.view.civictheme_views.yml
docroot/themes/contrib/civictheme/includes/listing.inc
docroot/themes/contrib/civictheme/includes/views.inc
tests/behat/features/paragraph.civictheme_listing.view.feature

1. Drupal core API changed for rendering exposed form separately from view (our listing component does not want this)
2. Turned off exposed form as  a block in listing
3. Deleted listing view pages and moved pages to new view `civictheme_listing_examples`
4. Updated the preprocessing of the view to occur at the view layer rather than paragraph layer
https://user-images.githubusercontent.com/57734756/169940213-347df0df-65aa-435b-ae44-a692b7f8093e.mp4
With the bigger listing change coming might look at whether we do all parapgraph setting preprocessing in the `civictheme_preprocess_views_view` layer rather than in the paragraph.

[CIVIC-631] Update listing form rendering for change to core.

---

docroot/themes/contrib/civictheme/README.md
docroot/themes/contrib/civictheme/civictheme_library/README.md
docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/input/input.scss
docroot/themes/contrib/civictheme/docs/namespaces.md
docroot/themes/contrib/civictheme/includes/mobile_navigation.inc

1. Check for menu items before accessing items property.
2. Updated docs to point to `README.md` rather than the non-existent `introduction.md`
3. Remove `margin-bottom` on hidden inputs

Check for menu items before accessing items.

---

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc
docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/03.general.inc
docroot/themes/contrib/civictheme/civictheme.info.yml
docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_custom_last_updated.yml
docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_custom_last_updated.yml
docroot/themes/contrib/civictheme/includes/banner.inc
tests/behat/features/content_type.civictheme_page.fields.feature
tests/behat/features/content_type.civictheme_page.view.feature

**Issue URL:** https://salsadigital.atlassian.net/browse/CIVIC-723
1.  Added a new date field "field_c_n_custom_last_updated" to Page Content type.
2. Added logic to show/hide this new field based on different variations of selecting "field_c_n_show_last_updated".
3. Added behat tests.
4. Updated generated content to include variations of all AC.
You will notice I used `$helper::randomDate('last month', 'now'),` because if I had used `$helper::randomDate()`, then the random date generated will always be today's date. There is a bug is the randomDate() function in the generated_content module. The bug is: The default for $start and $finish are both set to 'now'.

[CIVIC-723] Added "Last updated date" as a custom date for Page content type.

---

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/image/image.twig

I have added support for empty quotes as the alt attribute on the image component as this is an accessibility requirement: 
https://www.w3.org/WAI/tutorials/images/decorative/#:~:text=In%20these%20cases%2C%20a%20null,from%20that%20in%20adjacent%20text.
Current support for `role="presentation"` for delineating decorative images is not currently widely supported. An empty alt tag explicitly defined (e.g. `alt=""`) is more widely supported by screen readers. My change allows for empty string as an alt tag. 
1. Changed test from `is not empty` to `is not null` for outputting alt tags on images to support explicitly defining empty strings as alt tag attribute on image component.
Example test with empty alt tag versus no alt tag:

[CIVIC] Added support for empty string as alt attribute value on image component.

---

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/breadcrumb/breadcrumb.twig
tests/behat/features/breadcrumb.view.feature

https://salsadigital.atlassian.net/browse/CIVIC-960
1. Updated breadcrumb to show actual parent value on mobile

[CIVIC-960] Updated breadcrumb to show actual parent value on mobile.

---

docroot/themes/contrib/civictheme/civictheme.info.yml
docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_navigation_card.default.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_navigation_card.default.yml
docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_size.yml
docroot/themes/contrib/civictheme/includes/navigation_card.inc
tests/behat/features/paragraph.civictheme_navigation_card.fields.feature

https://salsadigital.atlassian.net/browse/CIVIC-957
1. Added Size field to Navigation card paragraph.
2. Added preprocess variable to extract the size value.

[CIVIC-957] Added Size field to Navigation card paragraph.

---

composer.json
composer.lock

https://salsadigital.atlassian.net/browse/CIVIC-969
1. **Updated all deps with `composer update --with-dependencies`**
- drupal/core-project-message updated from 9.4.2 to 9.4.5 patch
See changes: https://github.com/drupal/core-project-message/compare/9.4.2...9.4.5
Release notes: https://github.com/drupal/core-project-message/releases/tag/9.4.5
- symfony/config updated from v4.4.42 to v4.4.44 patch
See changes: https://github.com/symfony/config/compare/v4.4.42...v4.4.44
Release notes: https://github.com/symfony/config/releases/tag/v4.4.44
- drupal/core installed in version 9.3.19
Release notes: https://github.com/drupal/core/releases/tag/9.3.19
- phpunit/phpunit updated from 9.5.22 to 9.5.23 patch
See changes: https://github.com/sebastianbergmann/phpunit/compare/9.5.22.. …

[CIVIC-969] Updated to the latest dependencies.

---

docroot/themes/contrib/civictheme/includes/local_tasks.inc

https://salsadigital.atlassian.net/browse/CIVIC-974
1. Updated menu local task preprocess to utilise tabs weight.

[CIVIC-974] Fixed tabs order.

---

docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/b7f36176-620f-4178-aadd-9b448c610986.yml
docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/b7f36176-620f-4178-aadd-9b448c610986.yml
docroot/themes/contrib/civictheme/civictheme.info.yml
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.stories.js
docroot/themes/contrib/civictheme/config/install/core.entity_form_display.block_content.civictheme_mobile_navigation.default.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.block_content.civictheme_mobile_navigation.default.yml
docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_mobile_navigation.field_c_b_bottom.yml
docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_mobile_navigation.field_c_b_top.yml
docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_bottom.yml
docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_top.yml
docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
docroot/themes/contrib/civictheme/theme-settings.provision.inc
tests/behat/features/block_type.civictheme_mobile_navigation.fields.feature

https://salsadigital.atlassian.net/browse/CIVIC-976
1. Renamed Top menu (field_c_b_top_menu) to Top block (field_c_b_top).
2. Renamed Bottom menu (field_c_b_bottom_menu) to Bottom block (field_c_b_bottom).
3. Updated tests.
4. Updated generated content.
5. Fixed provisioning to add Primary navigation to the Top block and Secondary navigation to the Bottom block.

[CIVIC-976] Fixed missing menu block values added on build of a child theme.

---

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss

https://salsadigital.atlassian.net/browse/CIVIC-998
1. Fixed Icon colour to match the border colour of the Field message.

[CIVIC-998] Fixed Icon colour to match the border colour of the Field message.

---

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.stories.js
docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.twig

https://salsadigital.atlassian.net/browse/CIVIC-779
1. Implemented support to provide alt text if the icon is rendered in HTML mode.

[CIVIC-779] Implemented support to provide alt text if the icon is rendered in HTML mode.

---

docroot/themes/contrib/civictheme/includes/views.inc
tests/behat/features/paragraph.civictheme_listing.view.feature
tests/behat/features/view.civictheme_listing_examples.feature

https://salsadigital.atlassian.net/browse/CIVIC-1002
1. Updated behat test to check for exposed filters.
2. Changed to support only select, radios and checkboxes using CivicTheme’s components and render other types as-is.

[CIVIC-1002] Fixed not rendering exposed text filters  on views

---

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/grid/grid.stories.js
docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_grid.scss
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.twig
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-filter/basic-filter.twig
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/map/map.twig
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/card-container/card-container.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/fieldset/fieldset.stories.js
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.stories.js
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.twig
docroot/themes/contrib/civictheme/civictheme_library/components/04-templates/page/page.twig

https://salsadigital.atlassian.net/browse/CIVIC-992
1. Replaced instances of col-xs classes with col-xxs classes so that tiny mobile screens are not forgotten and still receive the column padding / formatting.
2. Replaced col-m- classes where that was being used as the smallest class.
3. Set container max-width to use vw instead of %

[CIVIC-992] Fixed layout classes for mobile.

---

docroot/modules/custom/civictheme_styleguide/components/page_title.inc
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.scss

https://salsadigital.atlassian.net/browse/CIVIC-766
1. Page title styleguide integration
2. Breadcrumb CSS fix
Before:
Page title

[CIVIC-766] Page title styleguide integration.

---

docroot/themes/contrib/civictheme/includes/alert.inc
tests/behat/features/content_type.civictheme_alert.view.feature

1. Fixed front-end naming for alerts data attribute.

Fixed alert test after CivicTheme renaming.

---

docroot/themes/contrib/civictheme/theme-settings.php

1. Changed default value in theme settings for the link.external_new_window to use link.external_new_window instead of the incorrect link.new_window

[CIVIC] Fix bug in theme settings for external new window.

---

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss

https://salsadigital.atlassian.net/browse/CIVIC-888
1. Fixed regression issue of Link component.
Hover > no underline should be displayed. Only colour should change.
Active > underline should be displayed with colour change.

[CIVIC-888] Fixed regression issue of Link component.

---

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-manual-list.html.twig

1. Fixed a typo in manual list template in Drupal theme twig.

[CIVIC] Fix list typo in Drupal template.

---

docroot/themes/contrib/civictheme/civictheme.libraries.yml
docroot/themes/contrib/civictheme/civictheme.theme
tests/behat/features/theme.settings.color.feature

Updated civictheme_library_info_alter to use the prefix of current theme.
https://salsadigital.atlassian.net/browse/CIVIC-1123
1.

[CIVIC-1123] Fixed color stylesheet generation to correclty handle active theme prefix.

---

docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_summary.yml

https://salsadigital.atlassian.net/browse/CIVIC-1189
1. Updated Navigation Card summary field to non-mandatory.

[CIVIC-1189] Updated Navigation Card summary field to non-mandatory.

---

docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml

https://salsadigital.atlassian.net/browse/CIVIC-1213
1. Removed summary field displayed from event content page.

[CIVIC-1213] Removed summary field displayed from event content page.

---

docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/optional/civictheme.settings.yml
docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/optional/civictheme.settings.yml
docroot/modules/custom/civictheme_content/modules/civictheme_content_government/config/optional/civictheme.settings.yml
docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/config/optional/civictheme.settings.yml
docroot/themes/contrib/civictheme/config/install/civictheme.settings.yml
docroot/themes/contrib/civictheme/config/schema/civictheme.schema.yml
docroot/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php

https://salsadigital.atlassian.net/browse/CIVIC-1216
1. Added summary length logic in settings
2. Updated default settings to include events card length in default profiles.

[CIVIC-1216] Implemented summary field config for events card component.

---

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig

1. Inherit the theme for the close button and menu links.
Before and after, demonstrating that close button inherits the theme.

[CIVIC] Fixed mobile menu theme inheritance.

---

docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.scss
docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.twig
tests/behat/features/content_type.civictheme_page.render.feature
tests/behat/features/paragraph.civictheme_manual_list.render.feature

https://salsadigital.atlassian.net/browse/CIVIC-1260
1. Updated `Item grid` to use unordered list.

[CIVIC-1260] Updated `Item grid` to use unordered list.

---

docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss
docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.twig

https://salsadigital.atlassian.net/browse/CIVIC-1242
1. Updated Navigation titles to correct heading H2.
2. Updated styles to use heading 5

[CIVIC-1242] Updated Navigation titles to correct heading H2.

---

docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/component.next_step.inc
docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_link.yml
docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_summary.yml
tests/behat/features/paragraph.civictheme_next_step.fields.feature

https://salsadigital.atlassian.net/browse/CIVIC-1313
1. Updated field configuration to make Summary and Link to be not required.
2. Updated Behat tests.
3. Verified preprocessors to make sure that empty Summary and Link are handled correctly.
4. Added 2 cases to the generated content: with empty summary, with empty link.

[CIVIC-1313] Updated Next steps content component.

---

docroot/themes/contrib/civictheme/civictheme.info.yml
docroot/themes/contrib/civictheme/config/install/core.entity_form_display.block_content.civictheme_banner.default.yml
docroot/themes/contrib/civictheme/config/install/core.entity_view_display.block_content.civictheme_banner.default.yml
docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_banner.field_c_b_banner_type.yml
docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_banner.field_c_b_featured_image.yml
docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_banner_type.yml
docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_featured_image.yml
docroot/themes/contrib/civictheme/includes/banner.inc
docroot/themes/contrib/civictheme/theme-settings.provision.inc
tests/behat/features/block_type.civictheme_banner.fields.feature
tests/behat/features/block_type.civictheme_banner.render.feature

https://salsadigital.atlassian.net/browse/CIVIC-1314
1. Added Type field field_c_b_banner_type with values Default and Large to Banner block.
2. Added Featured image field field_c_b_featured_image 
3. Updated banner preprocessing to use values from these 2 fields and allow to override with values in the page.
4. Updated _civictheme_provision__blocks__banner() to accommodate for the new fields
5. Updated Behat test to check banner overrides.

[CIVIC-1314] Updated banner block component to add Type and Featured image fields.

---

docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js
docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
docroot/themes/contrib/civictheme/includes/pager.inc
docroot/themes/contrib/civictheme/templates/navigation/pager.html.twig
docroot/themes/contrib/civictheme/templates/navigation/views-mini-pager.html.twig
tests/behat/features/pagination.render.feature

[https://salsadigital.atlassian.net/browse/CIVIC-1310](https://salsadigital.atlassian.net/browse/CIVIC-1310)
1. Updated ellipsis component to use single boolean.

[CIVIC-1310] Updated ellipsis component to use single boolean.

---

docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss

https://salsadigital.atlassian.net/browse/CIVIC-1325
1. Updated Link and Content Link component’s CSS to use word-break to break content.

[CIVIC-1325] Updated Link and Content Link component’s CSS to use word-break to break content.

---

docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_event_card.field_c_p_image.yml
tests/behat/features/paragraph.civictheme_event_card.fields.feature

https://salsadigital.atlassian.net/browse/CIVIC-1327
1. Updated Event card Image field to not be compulsory.

[CIVIC-1327] Updated Event card Image field to not be compulsory.

---

docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml

https://salsadigital.atlassian.net/browse/CIVIC-1332
1. Disabled the vertical spacing field value is rendering on Events page.

[CIVIC-1332] Disabled the vertical spacing field value is rendering on Events page.

---

composer.json
composer.lock

- stella-maris/clock removed (installed version was 0.1.7)
- drupal/core updated from 9.4.11 to 9.4.13 patch
See changes: https://github.com/drupal/core/compare/9.4.11...9.4.13
Release notes: https://github.com/drupal/core/releases/tag/9.4.13
- drupal/drupal-driver downgraded from v2.2.2 to dev-feature/drupal-10@03ae7c9 major
See changes: https://github.com/drevops/DrupalDriver/compare/jhedstrom:v2.2.2...drevops:03ae7c9
- drupal/drupal-extension downgraded from v4.2.1 to dev-feature/drupal-10@02d13f7 major
See changes: https://github.com/drevops/drupalextension/compare/jhedstrom:v4.2.1...drevops:02d13f7
- drevops/behat-steps updated from 1.4.3 to 1.5.2 minor
See changes: https://github.com/drevops/behat-steps/compare/1.4.3...1.5.2
Release notes: …

Updated dependencies.

---

docroot/themes/contrib/civictheme/config/install/civictheme.settings.yml
docroot/themes/contrib/civictheme/config/schema/civictheme.schema.yml
docroot/themes/contrib/civictheme/src/CivicthemeConfigManager.php
docroot/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php
tests/behat/features/theme.settings.components.feature

https://salsadigital.atlassian.net/browse/CIVIC-1438
1. Site slogan settings component in the theme settings page.

[CIVIC-1438] Added site slogan settings.

---

docroot/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php
tests/behat/features/theme.settings.components.feature

The Slogan field in the theme settings should not be required as not every site may have a slogan.

Updated site slogan in theme settings to be not required.

---

web/themes/contrib/civictheme/includes/utilities.inc

When retrieving a theme value from the component, a default value may be provided to be returned if the component does not have it's theme value set (in case of incorrectly programmatically-created components). 
In case where a default value is not provided, this leads to empty theme value being propagated to descendant components.

Fixed missing default theme value to default to 'light'.

---

tests/behat/features/links.feature
web/themes/contrib/civictheme/includes/utilities.inc

Issue: https://github.com/salsadigitalauorg/civictheme_source/issues/1147
1. Catch InvalidArgumentException in `civictheme_url_is_external()`.

[CIVIC-1521] Fixed issue #1147: catch InvalidArgumentException in civictheme_url_is_external

---

web/themes/contrib/civictheme/civictheme_library/components/00-base/flyout/flyout.js
web/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
web/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.scss
web/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.twig

https://salsadigital.atlassian.net/browse/CIVIC-1244
Changes:
- Updated use of 'links' component to 'buttons'. Links without href are not treated as interactive by the browser.
- Updated button styles to remove the default background color.
- Provide a consistent color for the focus ring.
- Added focus onto first link (after animation duration) when opening a flyout.
- Added focus on open trigger when closing a flyout.
- Added focus on first found trigger when closing all flyouts.
https://github.com/salsadigitalauorg/civictheme_source/assets/12739575/6246ec1a-a78b-450b-be08-630fe12a8900

[CIVIC-1244] Added a11y fixes for mobile menu.

---

tests/behat/features/paragraph.civictheme_automated_list.render.feature
web/themes/contrib/civictheme/includes/automated_list.inc

https://salsadigital.atlassian.net/browse/CIVIC-1449
changes, and they passed
1. Based on the component setting unset the view filter for automated list

[CIVIC-1449] Fixed Automated list filters not being hidden.

---

web/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.scss
web/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.twig

https://salsadigital.atlassian.net/browse/CIVIC-1502
1. Updated Group Filters with short-term fix for mobile style. This style was taken and modified from another civictheme project.
https://github.com/salsadigitalauorg/civictheme_source/assets/12739575/7d8578f9-5eaf-4860-8f90-e952db251007
https://github.com/salsadigitalauorg/civictheme_source/assets/12739575/f8650b57-e126-4aa0-bfb9-45b6177c1cda

[CIVIC-1502] Updated Group Filters with short-term fix for mobile style.

---

web/themes/contrib/civictheme/config/schema/civictheme.schema.yml
web/themes/contrib/civictheme/includes/paragraphs.inc
web/themes/contrib/civictheme/includes/snippet.inc
web/themes/contrib/civictheme/includes/utilities.inc
web/themes/contrib/civictheme/src/CivicthemeConstants.php
web/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php

https://www.drupal.org/project/civictheme/issues/3409009
1. Added summary settings for Snippet component.
2. Added an ability to use settings for other Snippet-base components (`civictheme_my_snippet`, `civictheme_my__other_snippet` etc.) if extended in sub-themes.
3. Fixed summary settings for cards not being correctly passed in views Rows style.

Issue #3409009 by alex.skrypnyk: Add summary settings for Snippet component.

---

tests/behat/features/search.feature
web/themes/contrib/civictheme/config/optional/search_api.index.civictheme_content.yml

https://www.drupal.org/project/civictheme/issues/3415747
1. Enable this processor for components fields.
al/assets/83997348/570ab839-72e4-41b2-8176-ebc0f6391886)

Issue #3415747 by joshua1234511: Search for Component title / summary field is not working

---

.circleci/config.yml
.docker/cli.dockerfile
.docker/cli.onlytheme.dockerfile
.docker/cli.sibling.dockerfile
.docker/mariadb.dockerfile
.docker/nginx-drupal.dockerfile
.docker/php.dockerfile
docker-compose.yml
web/themes/contrib/civictheme/includes/link.inc
web/themes/contrib/civictheme/includes/utilities.inc

After the latest upgrade local env wasn't working because of the package version change.
1. Tzdata package fix.
```
=> [mariadb internal] load build context                                                                                         0.2s
=> => transferring context: 301B                                                                                                 0.0s
=> [mariadb 1/3] FROM docker.io/uselagoon/mariadb-drupal:23.12.0@sha256:3f251b7f6da4f6620a9ca4941ae46e0980f9acd68aa18c5ecbda427  0.0s
=> CACHED [mariadb 2/3] COPY ./.docker/config/mariadb/my.cnf /etc/my.cnf.d/server.cnf                                            0.0s
=> CACHED [mariadb 3/3] RUN fix-permissions /etc/my.cnf.d/                                                                       0.0s
=> [mariadb] …
```

Updated containers to 24.1.0.

---

web/themes/contrib/civictheme/theme-settings/civictheme.theme-settings.colors.js

https://www.drupal.org/project/civictheme/issues/3415751
1. Fixed Duplicated checkboxes to show dependent colours on sub-theme settings.
[screencast-localhost_8000-2024.02.16-01_41_27.webm](https://github.com/civictheme/monorepo-drupal/assets/83997348/ff2e029c-3e12-4eeb-9eef-363ebb3a86c8)

Issue #3415751 by joshua1234511: Fixed Duplicated checkboxes to show dependent colours on sub-theme settings.

---

tests/behat/features/cache.render.feature
web/themes/contrib/civictheme/includes/banner.inc
web/themes/contrib/civictheme/includes/block_content.inc

https://www.drupal.org/project/civictheme/issues/3414639
1. Fixed Page titles cached as Access Denied Issue.

Issue #3414639 by joshua1234511, alex.skrypnyk:  Fixed banner shows page titles as "Access Denied" due to a block cache.

---

tests/behat/features/paragraph.civictheme_automated_list.render.feature
web/modules/custom/civictheme_dev/config/install/views.view.civictheme_automated_list_test.yml
web/themes/contrib/civictheme/config/install/views.view.civictheme_automated_list.yml

https://www.drupal.org/project/civictheme/issues/3415742
1. Updated the view config to exclude the current node.
2. Updated tests to check for the current node's absence.

Issue #3415742 by joshua1234511:  Fixed Nodes within an Automated list should not reference itself.

---

web/themes/contrib/civictheme/includes/menu.inc
web/themes/contrib/civictheme/includes/primary_navigation.inc
web/themes/contrib/civictheme/includes/secondary_navigation.inc

https://www.drupal.org/project/civictheme/issues/3421251
1. Added a flag for Expand all menu links, passed view block config. 
https://nimb.ws/UJdh0Wq
[screencast-monorepo-drupal.docker.amazee.io-2024.03.12-18_31_00.webm](https://github.com/civictheme/monorepo-drupal/assets/83997348/a5cb0f9c-e1f5-4821-81b9-2e6afb6b298f)

Issue #3421251] by joshua1234511, alex.skrypnyk: Navigation sidebar not expanding sub-links automatically

---

web/modules/custom/civictheme_content/modules/civictheme_content_default/content/menu_link_content/hhh6ae32-3h1b-495a-8263-a08302a80a32.yml
web/modules/custom/civictheme_dev/civictheme_dev.post_update.php

https://salsadigital.atlassian.net/browse/CIVIC-1707
1. Updated redirect in code to use themes/custom/civictheme_demo/storybook-static/index.html
2. Updated Default content profile to add a Storybook menu item before “Generated content” link in the secondary navigation in the header.

[CIVIC-1707] Created `Storybook` link in the secondary navigation and updated redirect.

---

web/themes/contrib/civictheme/package-lock.json
web/themes/contrib/civictheme/templates/block/block--menu-block--civictheme-primary-navigation.html.twig
web/themes/contrib/civictheme/templates/block/block--menu-block--civictheme-secondary-navigation.html.twig

https://github.com/civictheme/uikit/pull/113
1. Added conditional check (as per description above) to enforce inline if none is selected in block--menu-block--civictheme-primary-navigation.html.twig and block--menu-block--civictheme-secondary-navigation.html.twig

Issue #3422805 by joshua1234511 Updated conditional check for navigation to support updated Navigation component in UIKit.

---

tests/behat/features/paragraph.civictheme_promo.fields.feature
tests/behat/features/paragraph.civictheme_promo.render.feature
web/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/component.promo.inc
web/themes/contrib/civictheme/civictheme.info.yml
web/themes/contrib/civictheme/civictheme.post_update.php
web/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_promo.default.yml
web/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_promo.default.yml
web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_promo.field_c_p_background.yml
web/themes/contrib/civictheme/includes/promo.inc
web/themes/contrib/civictheme/tests/src/Functional/Update/CivicthemeUpdatePathBareTest.php
web/themes/contrib/civictheme/tests/src/Functional/Update/CivicthemeUpdatePathFilledTest.php

https://www.drupal.org/project/civictheme/issues/3432526
1. Added Background field to Promo Component.
2. Updated demo content.

Issue #3432526 by joshua1234511: Promo component does not have padding when used with a sidebar.

---

scripts/theme_excluded_configs.txt
tests/behat/bootstrap/FeatureContext.php
tests/behat/features/media.image_styles.feature
tests/behat/features/paragraph.civictheme_event_card.render.feature
tests/behat/features/paragraph.civictheme_navigation_card.render.feature
tests/behat/features/paragraph.civictheme_promo_card.render.feature
web/themes/contrib/civictheme/civictheme.info.yml
web/themes/contrib/civictheme/civictheme.post_update.php
web/themes/contrib/civictheme/composer.json
web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_image.default.yml
web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_image.media_library.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_campaign.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_event_card.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_medium.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_navigation_card.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_promo_banner.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_promo_card.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_publication_card.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_slider_slide.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_subject_card.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_thumbnail.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_topic_desktop.yml
web/themes/contrib/civictheme/config/install/image.style.civictheme_topic_mobile.yml
web/themes/contrib/civictheme/includes/campaign.inc
web/themes/contrib/civictheme/includes/cards.inc
web/themes/contrib/civictheme/includes/paragraphs.inc
web/themes/contrib/civictheme/includes/slider.inc
web/themes/contrib/civictheme/src/CivicthemeConstants.php
web/themes/contrib/civictheme/src/CivicthemeUpdateHelper.php

https://www.drupal.org/project/civictheme/issues/3415665
1. Updated image styles to use Focal Point module with the same dimensions as currently set.
2. Removed the current image actions. 
3. Exported configs as theme configs.
4. Added a dependency on `focal_point` module in `civictheme.info.yml` file.
5. Updated code to use existing image styles.

Issue #3415665 by joshua1234511: Utilize Focal Point module

---

web/themes/contrib/civictheme/templates/layout/layout--single-column-contained.html.twig
web/themes/contrib/civictheme/templates/layout/layout--single-column.html.twig

Issue Link: https://www.drupal.org/project/civictheme/issues/3441713
1. Inlined component layout template into drupal layout template:
see:
https://github.com/civictheme/uikit/blob/main/components/00-base/layout/content-layout--single-column.twig
https://github.com/civictheme/uikit/blob/main/components/00-base/layout/content-layout--single-column-contained.twig
This isn't a complete solution as it includes a ui kit component within the theme but demonstrates the fix required for the linked issue.

Issue #3441713 by RichardGaunt: Layout error when another theme renders a node.

---

web/themes/contrib/civictheme/civictheme.api.php
web/themes/contrib/civictheme/civictheme.layouts.yml
web/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml
web/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
web/themes/contrib/civictheme/includes/node.inc
web/themes/contrib/civictheme/includes/page.inc
web/themes/contrib/civictheme/includes/primary_navigation.inc
web/themes/contrib/civictheme/includes/secondary_navigation.inc
web/themes/contrib/civictheme/includes/utilities.inc
web/themes/contrib/civictheme/package-lock.json
web/themes/contrib/civictheme/templates/layout/layout--three-columns.html.twig

Chnaged:
- Added a 3col layout which is a copy of the `Layout` component. We cannot have components Twig-`@included` into layouts because layouts may be accessed from another theme (i know, weird).
- Added a hook that allows the consumer theme to decide what to do with the "conflicting" regions (see image below).
- Fixed the location of the content moderation form to sit above the page.

Added 3 column layout.

---

web/themes/contrib/civictheme/includes/utilities.inc

See https://www.drupal.org/project/civictheme/issues/3444381

Issue #3444381 by RichardGaunt, alex.skrypnyk: `civictheme_get_field_value` helper function does not process some common core field types.

---

web/themes/contrib/civictheme/templates/misc/status-messages.html.twig

https://www.drupal.org/project/civictheme/issues/3426551

Issue #3426551 by naveenvalecha, tanashin-kishimoto, alex.skrypnyk: Empty Drupal message when there are exceptions thrown.

---

web/themes/contrib/civictheme/theme-settings.provision.inc

https://www.drupal.org/project/civictheme/issues/3457992

Issue #3457992 by alex.skrypnyk: Allow excluding provision types in `civictheme_provision_cli()`.

---

web/themes/contrib/civictheme/theme-settings.provision.inc

https://www.drupal.org/project/civictheme/issues/3457993

Issue #3457993 by alex.skrypnyk: Provisioning script does not re-use existing block UUIDs'.

---

web/themes/contrib/civictheme/assets/sass/header/_header_admin.scss
web/themes/contrib/civictheme/assets/sass/theme.admin.scss

https://www.drupal.org/project/civictheme/issues/3464362
1. Added a fix for menu when the CivicTheme is rendered in the admin theme.

Issue #3464362 by joshua1234511: Mega menu broken for authenticated users

---

scripts/drevops/deploy-lagoon.sh

1. Updated deploy script for lagoon 3.0 CLI fix
https://github.com/drevops/scaffold/commit/f0bbe9e526e14e25b9b1d15bd13b937bb050cdea
Issue identified and diagnosed by Josh: https://app.circleci.com/pipelines/github/civictheme/monorepo-drupal/7730/workflows/f689c4d3-dc7d-4d43-bbfc-8792a9532784/jobs/25677?invite=true#step-105-994_37
Note for mapping short to long name parameters
```
Usage:
lagoon deploy pullrequest [flags]
Aliases:
pullrequest, r
Flags:
-N, --base-branch-name string   Pullrequest base branch name
-R, --base-branch-ref string    Pullrequest base branch reference hash
--buildvar stringArray      Add one or more build variables to deployment (--buildvar KEY1=VALUE1 [--buildvar KEY2=VALUE2])
-H, --head-branch-name string   Pullrequest head branch name
-M, --head-branch-ref …
```

Fix for Lagoon CLI 3.0.

---

.circleci/config.yml
composer.lock

1. Updated drupal core in repository to 10.3
2. Updated contrib modules
3. Updated circleci configuration to test against supported versions of Drupal
```
- drupal/core-project-message updated from 10.2.7 to 10.3.5 minor
See changes: https://github.com/drupal/core-project-message/compare/10.2.7...10.3.5
Release notes: https://github.com/drupal/core-project-message/releases/tag/10.3.5
- phpstan/phpstan updated from 1.11.5 to 1.12.3 minor
See changes: https://github.com/phpstan/phpstan/compare/1.11.5...1.12.3
Release notes: https://github.com/phpstan/phpstan/releases/tag/1.12.3
- phpstan/extension-installer updated from 1.4.1 to 1.4.3 patch
See changes: https://github.com/phpstan/extension-installer/compare/1.4.1...1.4.3
Release notes: …
```

Updated composer to Drupal 10.3.

---

tests/behat/features/paragraph.civictheme_promo.render.feature

Updated Behat Test.

---

web/themes/contrib/civictheme/includes/paragraphs.inc
web/themes/contrib/civictheme/includes/utilities.inc
web/themes/contrib/civictheme/src/CivicthemeConstants.php

https://www.drupal.org/project/civictheme/issues/3460512
1. Included an ellipsis when truncating.

Issue #3460512 by joshua1234511, richardgaunt, fionamorrison23, alexskrypnyk, alancole: Add ellipsis to truncated card summary.

---

web/themes/contrib/civictheme/.storybook/preview.js
web/themes/contrib/civictheme/civictheme_starter_kit/.storybook/preview.js

https://www.drupal.org/project/civictheme/issues/3476889
1. In React, passing a blank `[]` dependency into `useEffect()` will run the function on load. However, we want to re-run the Drupal.Behaviours on any prop change.
https://github.com/user-attachments/assets/1eb5b42a-4a2f-4038-8fcb-189b98990a8d

Issue #3476889 - Fixed useEffect only running on load due to blank deps.

---

web/themes/contrib/civictheme/civictheme.theme
web/themes/contrib/civictheme/includes/layout.inc
web/themes/contrib/civictheme/src/Plugin/Layout/ThreeColumnsLayout.php
web/themes/contrib/civictheme/templates/layout/layout--three-columns.html.twig

https://www.drupal.org/project/civictheme/issues/3476600
1. When creating a 3 col layout section in page builder, the option to configure vertical spacing (top, bottom, both) has now been added.

Issue #3476600: Adding a layout setting for controlling space around the layout.

---

web/themes/contrib/civictheme/assets/sass/page/_page.scss
web/themes/contrib/civictheme/assets/sass/theme.scss
web/themes/contrib/civictheme/civictheme_starter_kit/assets/sass/page/_page.scss
web/themes/contrib/civictheme/civictheme_starter_kit/assets/sass/theme.scss

https://github.com/civictheme/uikit/issues/392
1. A companion to https://github.com/civictheme/uikit/pull/402 . Moves the page level styling into Drupal theme.

[CIVIC-1937] Add page level styles into Drupal theme.

---

web/themes/contrib/civictheme/civictheme.post_update.php

If the Drupal view `civictheme_alerts` is already deleted, then if you update `civictheme` to run `civictheme_post_update_alert_visibility_validation()`, then you get an error, `Call to a member function setSyncing() on null`, when running drush updb.
See Drupal issue: https://www.drupal.org/project/civictheme/issues/3500869
See related issue: https://www.drupal.org/project/drupal/issues/3051453
https://www.drupal.org/project/civictheme/issues/3500869
Checking if config exists is standard.
Test not created minor fix. Very cumbersome to add test.
Ditto.
Screenshot not required

Issue #3500869 by silverham: Call to a member function setSyncing() on null if Drupal view is removed and post_update hook is run

---

tests/bats/assets.basetheme.bats
web/themes/contrib/civictheme/.storybook/preview.js
web/themes/contrib/civictheme/build.js
web/themes/contrib/civictheme/civictheme_starter_kit/.storybook/preview.js
web/themes/contrib/civictheme/civictheme_starter_kit/build.js
web/themes/contrib/civictheme/package.json

1. Create a `civictheme.storybook.css` file which replaces the `/theme/custom/MYTHEME/dist/assets/` path with `/assets/`, which is suitable for the storybook.
2. Currently this only runs for the main stylesheet. `.editor`, `.layout` are not used in storybook. `.stories` is only used in storybook, so this will use the `/assets/` path by default.

Fixed an issue in storybook, where the asset directory cannot be found.

---

web/themes/contrib/civictheme/src/CivicthemeConfigImporter.php

https://www.drupal.org/project/civictheme/issues/3505673
1. Added a fix for D11 - ArgumentCountError when using content provisioning functiong

Issue #3505673 by joshua1234511, richardgaunt, jezrsh, fionamorrison23: ArgumentCountError when using content provisioning functiong

---

web/themes/contrib/civictheme/includes/local_tasks.inc

1. Added check for boolean access value rather than just expecting an AccessInterface object
2. Added better check of link array properties in local tasks preprocessing.

[#3512157] Added better access check on local task links.

---

package-lock.json
web/themes/contrib/civictheme/includes/banner.inc
web/themes/contrib/civictheme/package-lock.json
web/themes/contrib/civictheme/package.json

1. Complimentary PR to [UI Kit PR](https://github.com/civictheme/uikit/pull/507) to add id to banner - this removes the second id being set on banners.

Issue #3513583 by alan.cole, danielgry, fionamorrison23: Updated skip link to use id on the main, or banner element

---

tests/phpunit/CivicthemeCreateSubthemeScriptUnitTest.php
web/themes/contrib/civictheme/build.js
web/themes/contrib/civictheme/civictheme_create_subtheme.php
web/themes/contrib/civictheme/civictheme_starter_kit/build.js

- Jira: https://salsadigital.atlassian.net/browse/CIVIC-2142
- Drupal: https://www.drupal.org/project/civictheme/issues/3516354
1. This script update provides a way for subthemes to automatically find the civictheme base class, assuming that the subtheme and base theme both live in the `themes` folder in Drupal.
2. This change was needed because the location of the civictheme base class can be different per implementation. Some projects use `/contrib/` and `/custom/`, some put all themes in the same parent directory.
3. If the parent theme is expected to live in a vastly different directory, the base theme class can still be set manually, e.g.
```js
const DIR_CIVICTHEME = config.base ? null : `/any/directory/path/civictheme`
```
4. This change also implements a few more checks for …

Issue #3516354: Update update script to automatically find CivicTheme directory

---

web/themes/contrib/civictheme/includes/automated_list.inc

Issue #3522098: Added passing of the CSS class from view display to a template for Automated List

---

web/themes/contrib/civictheme/civictheme.api.php

https://www.drupal.org/project/civictheme/issues/3518342
One string change in API example code to help others avoid confusion

Issue #3518342 by jdleonard: hook_civictheme_automated_list_view_info_alter example's content type is misleading

---

web/themes/contrib/civictheme/config/optional/views.view.civictheme_search.yml

https://www.drupal.org/project/civictheme/issues/3518669
View search order was Ascending, should be Descending.

Issue #3518669 by jdleonard: Search displays least relevant search results first

---

web/themes/contrib/civictheme/includes/views.inc

1. Fixed an error thrown for an Automated List filters when a label is not set.

#3522101 Fixed exception thrown when a filter has no label set.

---

tests/behat/features/content_type.civictheme_alert.view.feature
tests/behat/features/toc.render.feature
web/themes/contrib/civictheme/civictheme.theme
web/themes/contrib/civictheme/includes/node.inc

1. Added alert component libraries via civictheme_page_attachments_alter.
2. Updated TOC test (was skipping)
No change to components required.

[#3522639] Fixed alerts not showing on CivicTheme pages.
